// Define the structure for an image gallery, just like in activities
export type TeamImageGallery = {
  folder: string; // Member ka folder, jaise 'harshit-vyas'
  count: number;
  fileType: "jpg" | "png";
};

// Define the main structure for a single team member
export type TeamMember = {
  slug: string; // Unique URL-friendly name
  name: string;
  designation: string;
  category:  "Coordinator"  | "Faculty Advisor"| "Senior Advisor"  | "Core" |"Past Member";
  tags: string[]; // For the badge on the card, just like activities
  imageGallery: TeamImageGallery; // Har member ka apna image folder
  content: string; // Unki personal detail page ka content
};

// --- THE COMPLETE TEAM LIST ---
// Har member ki photo ke liye, unke slug naam ka folder banakar usmein 1.jpg, 2.jpg etc. daalna hai.
const teamData: TeamMember[] = [
  
  // --- FACULTY ADVISORS ---
  {
    slug: "dr-vivek-gupta",
    name: "Dr. Vivek Gupta",
    designation: "Faculty Advisor (2023 - Present)",
    category: "Faculty Advisor",
    tags: ["Advisor"],
    imageGallery: { folder: "dr-vivek-gupta", count: 1, fileType: "jpg" },
    content: `<h3>About</h3><p>Detailed bio for Dr. Vivek Gupta will be updated here.</p>`,
  },

  // --- CORE TEAM ---
  {
    slug: "harshit-vyas",
    name: "Harshit Vyas",
    designation: "Project Head",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "harshit-vyas", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Harshit Vyas will be updated here.</p>`,
  },
  {
    slug: "ojaswi-choudhary",
    name: "Ojaswi Choudhary",
    designation: "Contesting Head",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "ojaswi-choudhary", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Ojaswi Choudhary will be updated here.</p>`,
  },
  {
    slug: "saatvik-mangal",
    name: "Saatvik Mangal",
    designation: "Content Head",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "saatvik-mangal", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Saatvik Mangal will be updated here.</p>`,
  },
  {
    slug: "siddharth-amlavad",
    name: "Siddharth Amlavad",
    designation: "Webd Head",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "siddharth-amlavad", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Siddharth Amlavad will be updated here.</p>`,
  },
  {
    slug: "niharika",
    name: "Niharika",
    designation: "Collaboration Head",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "niharika", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Niharika will be updated here.</p>`,
  },
  {
    slug: "aryan-kashyap",
    name: "Aryan Kashyap",
    designation: "Design Head",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "aryan-kashyap", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Aryan Kashyap will be updated here.</p>`,
  },
  {
    slug: "mihir-chandra",
    name: "Mihir Chandra",
    designation: "Videography Head",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "mihir-chandra", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Mihir Chandra will be updated here.</p>`,
  },
  {
    slug: "anshika",
    name: "Anshika",
    designation: "Media Head",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "anshika", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Anshika will be updated here.</p>`,
  },
  {
    slug: "prathmesh-chourasiya",
    name: "Prathmesh Chourasiya",
    designation: "Publicity Head",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "prathmesh-chourasiya", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Prathmesh Chourasiya will be updated here.</p>`,
  },
  {
    slug: "monu-patil",
    name: "Monu Patil",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "monu-patil", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Monu Patil will be updated here.</p>`,
  },
  {
    slug: "vatsal-dhyani",
    name: "Vatsal Dhyani",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "vatsal-dhyani", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Vatsal Dhyani will be updated here.</p>`,
  },
  {
    slug: "salil-sharma",
    name: "Salil Sharma",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "salil-sharma", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Salil Sharma will be updated here.</p>`,
  },
  {
    slug: "khushi-rewar",
    name: "Khushi Rewar",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "khushi-rewar", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Khushi Rewar will be updated here.</p>`,
  },
  {
    slug: "sachin-raman",
    name: "Sachin Raman",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "sachin-raman", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Sachin Raman will be updated here.</p>`,
  },
  {
    slug: "prashant-singh",
    name: "Prashant Singh",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "prashant-singh", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Prashant Singh will be updated here.</p>`,
  },
  {
    slug: "ritika-meena",
    name: "Ritika Meena",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "ritika-meena", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Ritika Meena will be updated here.</p>`,
  },
  {
    slug: "vaibhav-gupta",
    name: "Vaibhav Gupta",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "vaibhav-gupta", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Vaibhav Gupta will be updated here.</p>`,
  },
  {
    slug: "harshita-singh",
    name: "Harshita Singh",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "harshita-singh", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Harshita Singh will be updated here.</p>`,
  },
  {
    slug: "kishan-kumar",
    name: "Kishan Kumar",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "kishan-kumar", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Kishan Kumar will be updated here.</p>`,
  },
  {
    slug: "jatin-prasad",
    name: "Jatin Prasad",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "jatin-prasad", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Jatin Prasad will be updated here.</p>`,
  },
  {
    slug: "manish-kumar",
    name: "Manish Kumar",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "manish-kumar", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Manish Kumar will be updated here.</p>`,
  },
  {
    slug: "anshu-kumar-mandal",
    name: "Anshu Kumar Mandal",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "anshu-kumar-mandal", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Anshu Kumar Mandal will be updated here.</p>`,
  },
  {
    slug: "aditya",
    name: "Aditya",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "aditya", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Aditya will be updated here.</p>`,
  },
  {
    slug: "abhinn",
    name: "Abhinn",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "abhinn", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Abhinn will be updated here.</p>`,
  },
  {
    slug: "tushar-bhati",
    name: "Tushar Bhati",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "tushar-bhati", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Tushar Bhati will be updated here.</p>`,
  },
  {
    slug: "shanti-devi",
    name: "Shanti Devi",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "shanti-devi", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Shanti Devi will be updated here.</p>`,
  },
  {
    slug: "sonu-kumar-meena",
    name: "Sonu Kumar Meena",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "sonu-kumar-meena", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Sonu Kumar Meena will be updated here.</p>`,
  },
  {
    slug: "rana-rohitashav-gehloch",
    name: "Rana Rohitashav Gehloch",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "rana-rohitashav-gehloch", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Rana Rohitashav Gehloch will be updated here.</p>`,
  },
  {
    slug: "mrinal-vora",
    name: "Mrinal Vora",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "mrinal-vora", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Mrinal Vora will be updated here.</p>`,
  },
  {
    slug: "manish-godara",
    name: "Manish Godara",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "manish-godara", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Manish Godara will be updated here.</p>`,
  },
  {
    slug: "abhinav-singh",
    name: "Abhinav Singh",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "abhinav-singh", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Abhinav Singh will be updated here.</p>`,
  },
  {
    slug: "ajeet",
    name: "Ajeet",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "ajeet", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Ajeet will be updated here.</p>`,
  },
  {
    slug: "alari-swargiaryaa",
    name: "Alari Swargiaryaa",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "alari-swargiaryaa", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Alari Swargiaryaa will be updated here.</p>`,
  },
  {
    slug: "deepak-kumar",
    name: "Deepak Kumar",
    designation: "Core-Team",
    category: "Core",
    tags: ["Core"],
    imageGallery: { folder: "deepak-kumar", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Deepak Kumar will be updated here.</p>`,
  },

  // --- COORDINATORS ---
  {
    slug: "khushi",
    name: "Khushi",
    designation: "Coordinator",
    category: "Coordinator",
    tags: ["Coordinator"],
    imageGallery: { folder: "khushi", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Khushi will be updated here.</p>`,
  },
  {
    slug: "aman-sharma",
    name: "Aman Sharma",
    designation: "Co-coordinator",
    category: "Coordinator",
    tags: ["Coordinator"],
    imageGallery: { folder: "aman-sharma", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Aman Sharma will be updated here.</p>`,
  },
  {
    slug: "sowmika-rao-samudrala",
    name: "Sowmika Rao Samudrala",
    designation: "Co-coordinator",
    category: "Coordinator",
    tags: ["Coordinator"],
    imageGallery: { folder: "sowmika-rao-samudrala", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Sowmika Rao Samudrala will be updated here.</p>`,
  },

  // --- SENIOR ADVISORS ---
  {
    slug: "gyanesh-ranjan-chauhan",
    name: "Gyanesh Ranjan Chauhan",
    designation: "Mentor",
    category: "Senior Advisor",
    tags: ["Mentor"],
    imageGallery: { folder: "gyanesh-ranjan-chauhan", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Gyanesh Ranjan Chauhan will be updated here.</p>`,
  },
  {
    slug: "dharkan-anand",
    name: "Dharkan Anand",
    designation: "Mentor",
    category: "Senior Advisor",
    tags: ["Mentor"],
    imageGallery: { folder: "dharkan-anand", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Dharkan Anand will be updated here.</p>`,
  },
  {
    slug: "rishav",
    name: "Rishav",
    designation: "Mentor",
    category: "Senior Advisor",
    tags: ["Mentor"],
    imageGallery: { folder: "rishav", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Rishav will be updated here.</p>`,
  },
  {
    slug: "rohit",
    name: "Rohit",
    designation: "Mentor",
    category: "Senior Advisor",
    tags: ["Mentor"],
    imageGallery: { folder: "rohit", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Rohit will be updated here.</p>`,
  },
  {
    slug: "aayushi-thakur",
    name: "Aayushi Thakur",
    designation: "Mentor",
    category: "Senior Advisor",
    tags: ["Mentor"],
    imageGallery: { folder: "aayushi-thakur", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Aayushi Thakur will be updated here.</p>`,
  },
  {
    slug: "devesh-ojha",
    name: "Devesh Ojha",
    designation: "Mentor",
    category: "Senior Advisor",
    tags: ["Mentor"],
    imageGallery: { folder: "devesh-ojha", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Devesh Ojha will be updated here.</p>`,
  },
  {
    slug: "pranshu-sharma",
    name: "Pranshu Sharma",
    designation: "Mentor",
    category: "Senior Advisor",
    tags: ["Mentor"],
    imageGallery: { folder: "pranshu-sharma", count: 1, fileType: "jpg" },
    content: `<h3>About Me</h3><p>Detailed bio for Pranshu Sharma will be updated here.</p>`,
  },

  // --- PAST MEMBERS (PAST FACULTY ADVISORS) ---
  {
    slug: "dericks-p-shukla",
    name: "Dericks P Shukla",
    designation: "Past Faculty Advisor (2019-2022)",
    category: "Past Member",
    tags: ["Past Advisor"],
    imageGallery: { folder: "dericks-p-shukla", count: 1, fileType: "jpg" },
    content: `<h3>Contributions</h3><p>Details about Dericks P Shukla's contributions will be updated here.</p>`,
  },
  {
    slug: "dr-kaustav-sarkar",
    name: "Dr. Kaustav Sarkar",
    designation: "Past Faculty Advisor (2017-2019)",
    category: "Past Member",
    tags: ["Past Advisor"],
    imageGallery: { folder: "dr-kaustav-sarkar", count: 1, fileType: "jpg" },
    content: `<h3>Contributions</h3><p>Details about Dr. Kaustav Sarkar's contributions will be updated here.</p>`,
  },
  {
    slug: "dr-deepak-swami",
    name: "Dr. Deepak Swami",
    designation: "Past Faculty Advisor (2015-2017)",
    category: "Past Member",
    tags: ["Past Advisor"],
    imageGallery: { folder: "dr-deepak-swami", count: 1, fileType: "jpg" },
    content: `<h3>Contributions</h3><p>Details about Dr. Deepak Swami's contributions will be updated here.</p>`,
  },
];

// Data ko category ke hisaab se sort karne ke liye (optional, but good practice)
const sortedTeamData = [...teamData].sort((a, b) => {
    const categoryOrder = ["Coordinator","Faculty Advisor","Senior Advisor","Core", "Past Member"];
    return categoryOrder.indexOf(a.category) - categoryOrder.indexOf(b.category);
});

export { sortedTeamData as teamData };
